### PR TITLE
Repl Support

### PR DESCRIPTION
**Pull request by maxswebservices**
just a suggestion, didnt even test

### CODE REVIEW

**Review by Null-n-V0id — APPROVED** [review]

**Review by Null-n-V0id — APPROVED** [review]

**Review by Null-n-V0id — CHANGES_REQUESTED** [review]
Why are these changes necessary for Repl.it support? Looks like a pretty drastic change to the dependencies list without much reason.

**Comment by maxswebservices** [comment]
Makes it fully automatic, like heroku deploy.
Without a .replit file and a package-lock.json it takes much more effort to configurate and run the file.
Will work on later

**Comment by maxswebservices** [comment]
Not really support, just a more automatic process

**Comment by Null-n-V0id** [comment]
> Makes it fully automatic, like heroku deploy. Without a .replit file and a package-lock.json it takes much more effort to configurate and run the file. Will work on later

what's with the changes to the package-lock.json?  none of those dependencies are used in any of my code.

**Pull request merged**
